apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-go-templating
spec:
  # Using latest because it provides the `include` function
  # package: xpkg.upbound.io/upbound/function-go-templating:v0.3.0
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:latest
